### ISSUE TITLE
A doubt of using Emitter

### ISSUE THREAD

**Issue by gaosh13** [nanndoj/react-native-particles#1]
When I was using this module in my project, I received a warning from the BaseEmitter.js.
The issue is that the BaseEmitter component continues to call 'setState' in _draw function even when it is unmounted. (It is better not to call setState() on unmounted components)
I fixed it by setting a flag to determine whether the component is mounted. Is it a better way to stop the loop when 'componentWillUnmount' is called?

**Comment by nanndoj** [comment]
Hi @gaosh13,
Thanks for your contribution. There is a better solution indeed. We need to cancel any scheduled callbacks when the component is unmounted. I will create a PR to fix it today.
