### ISSUE TITLE
Unlimited particleLife ?

### ISSUE THREAD

**Issue by torianBr** [nanndoj/react-native-particles#3]
How can I use  Unlimited particleLife ?

**Comment by nanndoj** [comment]
Hi @torianBr, 

To keep the performance, the particle is destroyed when it reaches the `particleLife` or go out of the scree boundaries. 

Its movements rely on the Animated API. Maybe we can use the loop function from that api to provide endless particleLife. 

What is the case that you need it?

**Comment by torianBr** [comment]
Thanks for your answer. I was testing your module to use with my AI.
