### ISSUE TITLE
Randomness

### ISSUE THREAD

**Issue by gamedolphin** [nanndoj/react-native-particles#4]
How would you suggest getting random particles with this component? And random emit timings and random numbers?

**Comment by adamck** [comment]
I used many emitters, each with random params. This setup uses a bunch of different emojis as particles. And `boundedRandom()` is my own helper function.

`arrayOfEmojiNames.map(emoji => createEmitter(emoji))`

```
const createEmitter = (name: string) =>
  <Emitter
    key={name}
    numberOfParticles={boundedRandom(5, 12)}
    emissionRate={1}
    interval={boundedRandom(1000, 3000)}
    particleLife={3000}
    direction={-90}
    spread={360}
    gravity={boundedRandom(5, 10)}
    speed={boundedRandom(25, 55)}
    fromPosition={{ x: 100, y: 100 }}>
      <Emoji name={name} style={{ fontSize: boundedRandom(15, 60) }} />
  </Emitter>
```

**Comment by nanndoj** [comment]
Yes! t is not a problem to have many emitters because they don't create any extra element (besides the particles created by it).

Also the `fromPosition` argument can accept a function instead of an object to help to randomize a bit more. Using @adamck example:

```diff
const createEmitter = (name: string) =>
  <Emitter
    key={name}
    numberOfParticles={boundedRandom(5, 12)}
    emissionRate={1}
    interval={boundedRandom(1000, 3000)}
    particleLife={3000}
    direction={-90}
    spread={360}
    gravity={boundedRandom(5, 10)}
    speed={boundedRandom(25, 55)}
-   fromPosition={{ x: 100, y: 100 }}
+   fromPosition={() => ({ x: randomFn(), y: randomFn() })}
   >
      <Emoji name={name} style={{ fontSize: boundedRandom(15, 60) }} />
  </Emitter>
```

**Comment by gamedolphin** [comment]
Makes sense. Thank you. I ended up writing my own version of this with randomness. 

Wonderful lib btw. GG!
