### ISSUE TITLE
stopEmitting callback 

### ISSUE THREAD

**Issue by bernhardt1** [nanndoj/react-native-particles#5]
It would be useful to have a stopEmitting callback.

My use case is to have some sparkles emitting from an element and then stop() them when the user presses the element.

**Comment by bernhardt1** [comment]
I added this to BaseEmitter for now. It seems to do the trick. Not sure if its optimal though :)

```
stop() {
    this.isEmitting = false;
    this.particlesCounter = 0;
    this.particles = [];
  }
```

**Comment by nanndoj** [comment]
hi @bernhardt1 ,

Thanks for using the library. It is totally fine to have a stop method like this. I'll make some tests today to see if calling `start()` again will work as expected. I'll keep you updated :)

**Comment by bernhardt1** [comment]
Awesoem, thanks for the library. It works great so far!

**Comment by fega** [comment]
@bernhardt1 I'm using your proposed solution but it doesn't work if the button is pressed quickly, there is any solution for this?

**Comment by bernhardt1** [comment]
@fega I haven't run into that issue.

What do you mean it doesn't work if pressed quickly? The emitter doesn't stop?

**Comment by fega** [comment]
I'm creating a particle every time when the user press a button, if the user presses to quickly, the button stops creating the particles

even if I wait before press again

**Comment by fega** [comment]
@nanndoj was this solved?
