### ISSUE TITLE
Current release is not live on npm

### ISSUE THREAD

**Issue by LightningXCE** [nanndoj/react-native-particles#8]
Hello!

Sorry to bug, but the npm package is behind the current github status, namely missing the Infinite Loop property.

Any chance that could be pushed? Thanks!

**Comment by nanndoj** [comment]
Sorry for the delay. I’ll push a new version today

**Comment by LightningXCE** [comment]
Oh not a problem! I was able to use the version you have here.

Thanks again for such an amazing tool!
